backend:
  name: github
  repo: infamous-lucifer/writing-portfolio
  branch: main
  base_url: https://sveltia-cms-auth.bikshat062.workers.dev

site_url: "https://infamous-lucifer.github.io/writing-portfolio"
display_url: "https://infamous-lucifer.github.io/writing-portfolio"

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Essays & Prose"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text", required: false}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Tags", name: "tags", widget: "list", default: ["essay"]}
      - {label: "Cover Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
